functionsDirectory = "/home/maciej/Dokumenty/svelte wlasne projekty/strona-ecpu/netlify/functions"
functionsDirectoryOrigin = "ui"

[build]
publish = "/home/maciej/Dokumenty/svelte wlasne projekty/strona-ecpu/build"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/home/maciej/Dokumenty/svelte wlasne projekty/strona-ecpu/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[plugins]]
origin = "ui"
package = "@netlify/plugin-lighthouse"
pinned_version = "6"

[plugins.inputs]

[[headers]]
for = "/_app/immutable/*"

[headers.values]
cache-control = "public, immutable, max-age=31536000"

[[redirects]]
from = "*"
to = "/.netlify/functions/sveltekit-render"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]