name = "strona-ecpu"
type = "javascript"  # lub "rust", "webpack" w zależności od projektu

[build]
command = "npm run build"
[build.upload]
format = "modules"  # lub "service-worker" w zależności od aplikacji

[env.production]
name = "development"
workers_dev = false
compatibility_date = "2024-08-06"  # Ustaw datę, którą chcesz używać
