import { c as create_ssr_component, e as escape } from "../../../chunks/ssr.js";
import "../../../chunks/client.js";
import "devalue";
import { t } from "../../../chunks/i18n.js";
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  return `<main class="flex flex-col items-center justify-center h-screen bg-gray-100 p-4 sm:p-6"><h1 class="text-3xl sm:text-5xl font-bold mb-1 mt-4 sm: mb-3 mt-0">${escape(t("registration"))}</h1> ${``} <form class="flex flex-col gap-4 p-6 sm:p-8 bg-white rounded-lg shadow-md w-full max-w-lg sm:max-w-3xl" method="post" action="?/signup"> <div class="flex flex-col sm:flex-row gap-4"><div class="flex-1"><label for="imie" class="block mb-2">${escape(t("first_name"))}:</label> <input type="text" id="imie" name="imie" required class="w-full p-2 border border-gray-300 rounded"> ${``}</div> <div class="flex-1"><label for="nazwisko" class="block mb-2">${escape(t("last_name"))}:</label> <input type="text" id="nazwisko" name="nazwisko" required class="w-full p-2 border border-gray-300 rounded"> ${``}</div></div>  <div class="flex flex-col sm:flex-row gap-4"><div class="flex-1"><label for="ranga" class="block mb-2">${escape(t("select_user_type"))}:</label> <select name="ranga" id="ranga" class="w-full p-2 border border-gray-300 rounded"><option value="0" data-svelte-h="svelte-pf7cwr">Admin</option><option value="1" data-svelte-h="svelte-6ejqhu">Boss</option><option value="2" data-svelte-h="svelte-115dvtd">User</option></select></div> <div class="flex-1"><label for="stanowisko" class="block mb-2">${escape(t("position"))}:</label> <input type="text" id="stanowisko" name="stanowisko" class="w-full p-2 border border-gray-300 rounded"> ${``}</div></div>  <div class="flex flex-col sm:flex-row gap-4"><div class="flex-1"><label for="cardID" class="block mb-2">${escape(t("card_code"))}:</label> <input type="text" id="cardID" name="cardID" class="w-full p-2 border border-gray-300 rounded"> ${``}</div> <div class="flex-1"><label for="fingerID" class="block mb-2">${escape(t("fingerprint_code"))}:</label> <input type="text" id="fingerID" name="fingerID" class="w-full p-2 border border-gray-300 rounded"> ${``}</div></div>  <div class="flex flex-col sm:flex-row gap-4"><div class="flex-1"><label for="username" class="block mb-2">${escape(t("username"))}:</label> <input type="text" id="username" name="username" required class="w-full p-2 border border-gray-300 rounded"> ${``}</div> <div class="flex-1"><label for="password" class="block mb-2">${escape(t("password"))}:</label> <input type="password" id="password" name="password" required class="w-full p-2 border border-gray-300 rounded"> ${``}</div></div> <button type="submit" class="w-full py-3 bg-blue-500 text-white rounded hover:bg-blue-600">${escape(t("registration"))}</button></form></main>`;
});
export {
  Page as default
};
