import { c as create_ssr_component } from "../../../chunks/ssr.js";
import "../../../chunks/client.js";
import "devalue";
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  return `<main class="flex flex-col items-center justify-center h-screen bg-gray-100 p-6"><h1 class="text-5xl font-bold mb-4" data-svelte-h="svelte-l90g2f">Rejestracja</h1> <h1 class="text-5xl font-bold mb-4" data-svelte-h="svelte-c47igp"></h1> ${``} <form class="flex flex-col gap-4 p-8 bg-white rounded-lg shadow-md w-full max-w-3xl" method="post"> <div class="flex gap-4"><div class="flex-1"><label for="imie" class="block mb-2" data-svelte-h="svelte-18uejv6">Imie:</label> <input type="text" id="imie" name="imie" required class="w-full p-2 border border-gray-300 rounded"> ${``}</div> <div class="flex-1"><label for="nazwisko" class="block mb-2" data-svelte-h="svelte-1ize8du">Nazwisko:</label> <input type="text" id="nazwisko" name="nazwisko" required class="w-full p-2 border border-gray-300 rounded"> ${``}</div></div>  <div class="flex gap-4"><div class="flex-1"><label for="ranga" class="block mb-2" data-svelte-h="svelte-44tfi0">Wybierz typ użytkownika:</label> <select name="ranga" id="ranga" class="w-full p-2 border border-gray-300 rounded"><option value="0" data-svelte-h="svelte-1tswdx1">Administrator</option><option value="1" data-svelte-h="svelte-6ejqhu">Boss</option><option value="2" data-svelte-h="svelte-10kpufd">Użytkownik</option></select></div> <div class="flex-1"><label for="stanowisko" class="block mb-2" data-svelte-h="svelte-34yity">Stanowisko:</label> <input type="text" id="stanowisko" name="stanowisko" class="w-full p-2 border border-gray-300 rounded"> ${``}</div></div>  <div class="flex gap-4"><div class="flex-1"><label for="cardID" class="block mb-2" data-svelte-h="svelte-mgxoq6">Kod Karty:</label> <input type="text" id="cardID" name="cardID" class="w-full p-2 border border-gray-300 rounded"> ${``}</div> <div class="flex-1"><label for="fingerID" class="block mb-2" data-svelte-h="svelte-rbivwt">Kod Odcisku Palca:</label> <input type="text" id="fingerID" name="fingerID" class="w-full p-2 border border-gray-300 rounded"> ${``}</div></div>  <div class="flex gap-4"><div class="flex-1"><label for="username" class="block mb-2" data-svelte-h="svelte-11t9gkp">Nazwa użytkownika:</label> <input type="text" id="username" name="username" required class="w-full p-2 border border-gray-300 rounded"> ${``}</div> <div class="flex-1"><label for="password" class="block mb-2" data-svelte-h="svelte-1f70in4">Hasło:</label> <input type="password" id="password" name="password" required class="w-full p-2 border border-gray-300 rounded"> ${``}</div></div> <button type="submit" class="w-full py-2 bg-blue-500 text-white rounded hover:bg-blue-600" data-svelte-h="svelte-1cc3tt2">Zarejestruj się</button></form></main>`;
});
export {
  Page as default
};
